# fly.toml app configuration file generated for my-sveltekit on 2023-10-30T19:00:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-sveltekit"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
