name: GitHub Actions Push to Fly_io
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: 'My ESLint',
    runs-on: ubuntu-latest
    stpes:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          # cache: npm
          # cache-dependency-path: ./package.json
          node-version: 16
      - name: 'Download deps'
        run: npm install
      - name: 'Lint'
        run: npm run lint